language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
install:
  - "gem install rspec"
  - "gem install codeclimate-test-reporter"
  - "gem install require_all"
script:
  - "sh ./runTests.sh"
addons:
   code_climate:
      repo_token: 0c5f40d542e87863cd64d9e3adcb34a801923367e018cf16d53537590e4d60b3
